//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Vts.Gui.Wpf.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Vts.Gui.Wpf.Resources.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string Button_Cancel {
            get {
                return ResourceManager.GetString("Button_Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel Save.
        /// </summary>
        public static string Button_CancelSave {
            get {
                return ResourceManager.GetString("Button_CancelSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel Simulation.
        /// </summary>
        public static string Button_CancelSimulation {
            get {
                return ResourceManager.GetString("Button_CancelSimulation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear All.
        /// </summary>
        public static string Button_ClearAll {
            get {
                return ResourceManager.GetString("Button_ClearAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear Newest.
        /// </summary>
        public static string Button_ClearNewest {
            get {
                return ResourceManager.GetString("Button_ClearNewest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download Prototype Input Files.
        /// </summary>
        public static string Button_DownloadPrototypeInputFiles {
            get {
                return ResourceManager.GetString("Button_DownloadPrototypeInputFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export Data.
        /// </summary>
        public static string Button_ExportData {
            get {
                return ResourceManager.GetString("Button_ExportData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export As Image.
        /// </summary>
        public static string Button_ExportImage {
            get {
                return ResourceManager.GetString("Button_ExportImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Generate Fluence/Interrogation Map.
        /// </summary>
        public static string Button_GenerateFluence {
            get {
                return ResourceManager.GetString("Button_GenerateFluence", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Run Inverse Solver.
        /// </summary>
        public static string Button_InverseSolver {
            get {
                return ResourceManager.GetString("Button_InverseSolver", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Load Input File.
        /// </summary>
        public static string Button_LoadInputFile {
            get {
                return ResourceManager.GetString("Button_LoadInputFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Plot Initial Guess.
        /// </summary>
        public static string Button_PlotInitialGuess {
            get {
                return ResourceManager.GetString("Button_PlotInitialGuess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Plot Measured Data.
        /// </summary>
        public static string Button_PlotMeasured {
            get {
                return ResourceManager.GetString("Button_PlotMeasured", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Plot μa Spectrum.
        /// </summary>
        public static string Button_PlotMua {
            get {
                return ResourceManager.GetString("Button_PlotMua", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Plot μs&apos; Spectrum.
        /// </summary>
        public static string Button_PlotMusPrime {
            get {
                return ResourceManager.GetString("Button_PlotMusPrime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Plot Reflectance.
        /// </summary>
        public static string Button_PlotReflectance {
            get {
                return ResourceManager.GetString("Button_PlotReflectance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset Values.
        /// </summary>
        public static string Button_ResetValues {
            get {
                return ResourceManager.GetString("Button_ResetValues", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Run Simulation.
        /// </summary>
        public static string Button_RunSimulation {
            get {
                return ResourceManager.GetString("Button_RunSimulation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save Simulation Results.
        /// </summary>
        public static string Button_SaveSimulationResults {
            get {
                return ResourceManager.GetString("Button_SaveSimulationResults", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update.
        /// </summary>
        public static string Button_Update {
            get {
                return ResourceManager.GetString("Button_Update", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Temporal Frequencies.
        /// </summary>
        public static string IndependentVariableAxis_Ft {
            get {
                return ResourceManager.GetString("IndependentVariableAxis_Ft", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Spatial Frequencies.
        /// </summary>
        public static string IndependentVariableAxis_Fx {
            get {
                return ResourceManager.GetString("IndependentVariableAxis_Fx", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Detector Positions.
        /// </summary>
        public static string IndependentVariableAxis_Rho {
            get {
                return ResourceManager.GetString("IndependentVariableAxis_Rho", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Detection Times.
        /// </summary>
        public static string IndependentVariableAxis_Time {
            get {
                return ResourceManager.GetString("IndependentVariableAxis_Time", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wavelengths.
        /// </summary>
        public static string IndependentVariableAxis_Wavelength {
            get {
                return ResourceManager.GetString("IndependentVariableAxis_Wavelength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Absorber Concentrations.
        /// </summary>
        public static string Label_AbsorberConcentrations {
            get {
                return ResourceManager.GetString("Label_AbsorberConcentrations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  (Air).
        /// </summary>
        public static string Label_Air {
            get {
                return ResourceManager.GetString("Label_Air", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Analog.
        /// </summary>
        public static string Label_Analog {
            get {
                return ResourceManager.GetString("Label_Analog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A(fx,z).
        /// </summary>
        public static string Label_AOfFxAndZ {
            get {
                return ResourceManager.GetString("Label_AOfFxAndZ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A(fx,z,ft).
        /// </summary>
        public static string Label_AOfFxAndZAndFt {
            get {
                return ResourceManager.GetString("Label_AOfFxAndZAndFt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A(fx,z,t).
        /// </summary>
        public static string Label_AOfFxAndZAndTime {
            get {
                return ResourceManager.GetString("Label_AOfFxAndZAndTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A(ρ,z).
        /// </summary>
        public static string Label_AOfRhoAndZ {
            get {
                return ResourceManager.GetString("Label_AOfRhoAndZ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A(ρ,z,ft).
        /// </summary>
        public static string Label_AOfRhoAndZAndFt {
            get {
                return ResourceManager.GetString("Label_AOfRhoAndZAndFt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A(ρ,z,t).
        /// </summary>
        public static string Label_AOfRhoAndZAndTime {
            get {
                return ResourceManager.GetString("Label_AOfRhoAndZAndTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to at.
        /// </summary>
        public static string Label_At {
            get {
                return ResourceManager.GetString("Label_At", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to At λ [nm] =.
        /// </summary>
        public static string Label_Atnm {
            get {
                return ResourceManager.GetString("Label_Atnm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Auto Scale.
        /// </summary>
        public static string Label_AutoScale {
            get {
                return ResourceManager.GetString("Label_AutoScale", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Auto-X.
        /// </summary>
        public static string Label_AutoScaleX {
            get {
                return ResourceManager.GetString("Label_AutoScaleX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Auto-Y.
        /// </summary>
        public static string Label_AutoScaleY {
            get {
                return ResourceManager.GetString("Label_AutoScaleY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Absorption Weighting Type:.
        /// </summary>
        public static string Label_AWT {
            get {
                return ResourceManager.GetString("Label_AWT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Basic Info.
        /// </summary>
        public static string Label_BasicInfo {
            get {
                return ResourceManager.GetString("Label_BasicInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Blood Concentration.
        /// </summary>
        public static string Label_BloodConcentration {
            get {
                return ResourceManager.GetString("Label_BloodConcentration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Blood volume [vol. frac.]:.
        /// </summary>
        public static string Label_BloodVolume {
            get {
                return ResourceManager.GetString("Label_BloodVolume", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Single-λ Calculator.
        /// </summary>
        public static string Label_Calculator {
            get {
                return ResourceManager.GetString("Label_Calculator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Colormap Type:.
        /// </summary>
        public static string Label_ColormapType {
            get {
                return ResourceManager.GetString("Label_ColormapType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Continuous.
        /// </summary>
        public static string Label_Continuous {
            get {
                return ResourceManager.GetString("Label_Continuous", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Discrete.
        /// </summary>
        public static string Label_Discrete {
            get {
                return ResourceManager.GetString("Label_Discrete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ellipsoid Region.
        /// </summary>
        public static string Label_EllipsoidRegion {
            get {
                return ResourceManager.GetString("Label_EllipsoidRegion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Φ(fx,z).
        /// </summary>
        public static string Label_FluenceOfFxAndZ {
            get {
                return ResourceManager.GetString("Label_FluenceOfFxAndZ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Φ(fx,z,ft).
        /// </summary>
        public static string Label_FluenceOfFxAndZAndFt {
            get {
                return ResourceManager.GetString("Label_FluenceOfFxAndZAndFt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Φ(fx,z,t).
        /// </summary>
        public static string Label_FluenceOfFxAndZAndTime {
            get {
                return ResourceManager.GetString("Label_FluenceOfFxAndZAndTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Φ(ρ,z).
        /// </summary>
        public static string Label_FluenceOfRhoAndZ {
            get {
                return ResourceManager.GetString("Label_FluenceOfRhoAndZ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Φ(ρ,z,ft).
        /// </summary>
        public static string Label_FluenceOfRhoAndZAndFt {
            get {
                return ResourceManager.GetString("Label_FluenceOfRhoAndZAndFt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Φ(ρ,z,t).
        /// </summary>
        public static string Label_FluenceOfRhoAndZAndTime {
            get {
                return ResourceManager.GetString("Label_FluenceOfRhoAndZAndTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Forward Simulation.
        /// </summary>
        public static string Label_ForwardSimulation {
            get {
                return ResourceManager.GetString("Label_ForwardSimulation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fwd Solver:.
        /// </summary>
        public static string Label_ForwardSolver {
            get {
                return ResourceManager.GetString("Label_ForwardSolver", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Frequency-Domain.
        /// </summary>
        public static string Label_FrequencyDomain {
            get {
                return ResourceManager.GetString("Label_FrequencyDomain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gaussian Beam Diameter:.
        /// </summary>
        public static string Label_GaussianBeam {
            get {
                return ResourceManager.GetString("Label_GaussianBeam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hide Key.
        /// </summary>
        public static string Label_HideKey {
            get {
                return ResourceManager.GetString("Label_HideKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hold On.
        /// </summary>
        public static string Label_HoldOn {
            get {
                return ResourceManager.GetString("Label_HoldOn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Independent Axis.
        /// </summary>
        public static string Label_IndependentAxis {
            get {
                return ResourceManager.GetString("Label_IndependentAxis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Initial Guess.
        /// </summary>
        public static string Label_InitialGuess {
            get {
                return ResourceManager.GetString("Label_InitialGuess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inv Solver:.
        /// </summary>
        public static string Label_InverseSolver {
            get {
                return ResourceManager.GetString("Label_InverseSolver", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check out this useful manipulation tool .
        /// </summary>
        public static string Label_JSONTool {
            get {
                return ResourceManager.GetString("Label_JSONTool", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://www.jsoneditoronline.org.
        /// </summary>
        public static string Label_JSONUrl {
            get {
                return ResourceManager.GetString("Label_JSONUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Layer .
        /// </summary>
        public static string Label_Layer {
            get {
                return ResourceManager.GetString("Label_Layer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Layer Height.
        /// </summary>
        public static string Label_LayerHeight {
            get {
                return ResourceManager.GetString("Label_LayerHeight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Max:.
        /// </summary>
        public static string Label_Max {
            get {
                return ResourceManager.GetString("Label_Max", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Max X:.
        /// </summary>
        public static string Label_MaxX {
            get {
                return ResourceManager.GetString("Label_MaxX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Max Y:.
        /// </summary>
        public static string Label_MaxY {
            get {
                return ResourceManager.GetString("Label_MaxY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mean Depth:.
        /// </summary>
        public static string Label_MeanDepth {
            get {
                return ResourceManager.GetString("Label_MeanDepth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to n_rel.
        /// </summary>
        public static string Label_MieNRel {
            get {
                return ResourceManager.GetString("Label_MieNRel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mie scattering law:.
        /// </summary>
        public static string Label_MieScatteringLaw {
            get {
                return ResourceManager.GetString("Label_MieScatteringLaw", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Min:.
        /// </summary>
        public static string Label_Min {
            get {
                return ResourceManager.GetString("Label_Min", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Min X:.
        /// </summary>
        public static string Label_MinX {
            get {
                return ResourceManager.GetString("Label_MinX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Min Y:.
        /// </summary>
        public static string Label_MinY {
            get {
                return ResourceManager.GetString("Label_MinY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modulation Frequency:.
        /// </summary>
        public static string Label_ModulationFrequency {
            get {
                return ResourceManager.GetString("Label_ModulationFrequency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to allow multi-axis selection.
        /// </summary>
        public static string Label_MultiAxisSelection {
            get {
                return ResourceManager.GetString("Label_MultiAxisSelection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -rho_max.
        /// </summary>
        public static string Label_NegRhoMax {
            get {
                return ResourceManager.GetString("Label_NegRhoMax", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Normalization:.
        /// </summary>
        public static string Label_Normalization {
            get {
                return ResourceManager.GetString("Label_Normalization", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of Photons:.
        /// </summary>
        public static string Label_NumberOfPhotons {
            get {
                return ResourceManager.GetString("Label_NumberOfPhotons", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Opt. Prop..
        /// </summary>
        public static string Label_OP {
            get {
                return ResourceManager.GetString("Label_OP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Optical Properties:.
        /// </summary>
        public static string Label_OpticalProperties {
            get {
                return ResourceManager.GetString("Label_OpticalProperties", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Optimization Parameters.
        /// </summary>
        public static string Label_OptimizationParameters {
            get {
                return ResourceManager.GetString("Label_OptimizationParameters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Optimizer Type.
        /// </summary>
        public static string Label_OptimizerType {
            get {
                return ResourceManager.GetString("Label_OptimizerType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to % noise.
        /// </summary>
        public static string Label_PercentNoise {
            get {
                return ResourceManager.GetString("Label_PercentNoise", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phase Function Type:.
        /// </summary>
        public static string Label_PhaseFunctionType {
            get {
                return ResourceManager.GetString("Label_PhaseFunctionType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to phd(fx,z).
        /// </summary>
        public static string Label_PHDOfFxAndZ {
            get {
                return ResourceManager.GetString("Label_PHDOfFxAndZ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to phd(fx,z,ft).
        /// </summary>
        public static string Label_PHDOfFxAndZAndFt {
            get {
                return ResourceManager.GetString("Label_PHDOfFxAndZAndFt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to phd(fx,z,t).
        /// </summary>
        public static string Label_PHDOfFxAndZAndTime {
            get {
                return ResourceManager.GetString("Label_PHDOfFxAndZAndTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to phd(ρ,z).
        /// </summary>
        public static string Label_PHDOfRhoAndZ {
            get {
                return ResourceManager.GetString("Label_PHDOfRhoAndZ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to phd(ρ,z,ft).
        /// </summary>
        public static string Label_PHDOfRhoAndZAndFt {
            get {
                return ResourceManager.GetString("Label_PHDOfRhoAndZAndFt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to phd(ρ,z,t).
        /// </summary>
        public static string Label_PHDOfRhoAndZAndTime {
            get {
                return ResourceManager.GetString("Label_PHDOfRhoAndZAndTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Plot Label:.
        /// </summary>
        public static string Label_PlotLabel {
            get {
                return ResourceManager.GetString("Label_PlotLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Plot Toggle:.
        /// </summary>
        public static string Label_PlotToggle {
            get {
                return ResourceManager.GetString("Label_PlotToggle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Plot Type:.
        /// </summary>
        public static string Label_PlotType {
            get {
                return ResourceManager.GetString("Label_PlotType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to +rho_max.
        /// </summary>
        public static string Label_PosRhoMax {
            get {
                return ResourceManager.GetString("Label_PosRhoMax", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Power law: .
        /// </summary>
        public static string Label_PowerLaw {
            get {
                return ResourceManager.GetString("Label_PowerLaw", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (A = μs&apos; at 1000nm).
        /// </summary>
        public static string Label_PowerLawDefinitionA {
            get {
                return ResourceManager.GetString("Label_PowerLawDefinitionA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Random Number Generator Type:.
        /// </summary>
        public static string Label_RandomNumberGeneratorType {
            get {
                return ResourceManager.GetString("Label_RandomNumberGeneratorType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ρ (Rho) Range:.
        /// </summary>
        public static string Label_RhoRange {
            get {
                return ResourceManager.GetString("Label_RhoRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to R(fx).
        /// </summary>
        public static string Label_ROfFx {
            get {
                return ResourceManager.GetString("Label_ROfFx", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to R(fx,ft).
        /// </summary>
        public static string Label_ROfFxAndFt {
            get {
                return ResourceManager.GetString("Label_ROfFxAndFt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to R(fx,t).
        /// </summary>
        public static string Label_ROfFxAndTime {
            get {
                return ResourceManager.GetString("Label_ROfFxAndTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to R(ρ).
        /// </summary>
        public static string Label_ROfRho {
            get {
                return ResourceManager.GetString("Label_ROfRho", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to R(ρ,ft).
        /// </summary>
        public static string Label_ROfRhoAndFt {
            get {
                return ResourceManager.GetString("Label_ROfRhoAndFt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to R(ρ,t).
        /// </summary>
        public static string Label_ROfRhoAndTime {
            get {
                return ResourceManager.GetString("Label_ROfRhoAndTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scaling Type:.
        /// </summary>
        public static string Label_ScalingType {
            get {
                return ResourceManager.GetString("Label_ScalingType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to scatter radius.
        /// </summary>
        public static string Label_ScatteringRadius {
            get {
                return ResourceManager.GetString("Label_ScatteringRadius", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Seed:.
        /// </summary>
        public static string Label_Seed {
            get {
                return ResourceManager.GetString("Label_Seed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Currently selected region:.
        /// </summary>
        public static string Label_SelectedRegion {
            get {
                return ResourceManager.GetString("Label_SelectedRegion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SimulationOptions.
        /// </summary>
        public static string Label_SimulationOptions {
            get {
                return ResourceManager.GetString("Label_SimulationOptions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Source Detector Separation:.
        /// </summary>
        public static string Label_SourceDetector {
            get {
                return ResourceManager.GetString("Label_SourceDetector", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Specify Inputs From File (recommended).
        /// </summary>
        public static string Label_SpecifyInputsFromFile {
            get {
                return ResourceManager.GetString("Label_SpecifyInputsFromFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start/Stop:.
        /// </summary>
        public static string Label_StartStop {
            get {
                return ResourceManager.GetString("Label_StartStop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Steady-State.
        /// </summary>
        public static string Label_SteadyState {
            get {
                return ResourceManager.GetString("Label_SteadyState", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to StO2 [frac.]:.
        /// </summary>
        public static string Label_StO2 {
            get {
                return ResourceManager.GetString("Label_StO2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time-Domain.
        /// </summary>
        public static string Label_TimeDomain {
            get {
                return ResourceManager.GetString("Label_TimeDomain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  (Tissue).
        /// </summary>
        public static string Label_Tissue {
            get {
                return ResourceManager.GetString("Label_Tissue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tissue Input.
        /// </summary>
        public static string Label_TissueInput {
            get {
                return ResourceManager.GetString("Label_TissueInput", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tissue Types.
        /// </summary>
        public static string Label_TissueTypes {
            get {
                return ResourceManager.GetString("Label_TissueTypes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total Hb [μM]:.
        /// </summary>
        public static string Label_TotalHb {
            get {
                return ResourceManager.GetString("Label_TotalHb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Track Statistics.
        /// </summary>
        public static string Label_TrackStatistics {
            get {
                return ResourceManager.GetString("Label_TrackStatistics", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to use spectral panel inputs.
        /// </summary>
        public static string Label_UseSpectralPanel {
            get {
                return ResourceManager.GetString("Label_UseSpectralPanel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Voxel Region.
        /// </summary>
        public static string Label_VoxelRegion {
            get {
                return ResourceManager.GetString("Label_VoxelRegion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to X Axis Spacing:.
        /// </summary>
        public static string Label_XAxisSpacing {
            get {
                return ResourceManager.GetString("Label_XAxisSpacing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Y Axis Spacing:.
        /// </summary>
        public static string Label_YAxisSpacing {
            get {
                return ResourceManager.GetString("Label_YAxisSpacing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to z=0.
        /// </summary>
        public static string Label_Z0 {
            get {
                return ResourceManager.GetString("Label_Z0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to z_max.
        /// </summary>
        public static string Label_ZMax {
            get {
                return ResourceManager.GetString("Label_ZMax", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to z Range:.
        /// </summary>
        public static string Label_zRange {
            get {
                return ResourceManager.GetString("Label_zRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GHz.
        /// </summary>
        public static string Measurement_GHz {
            get {
                return ResourceManager.GetString("Measurement_GHz", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to mm-1.
        /// </summary>
        public static string Measurement_Inv_mm {
            get {
                return ResourceManager.GetString("Measurement_Inv_mm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to mm.
        /// </summary>
        public static string Measurement_mm {
            get {
                return ResourceManager.GetString("Measurement_mm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saving simulation results....
        /// </summary>
        public static string Message_SaveSimulationResults {
            get {
                return ResourceManager.GetString("Message_SaveSimulationResults", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select a location to save the simulation statistics, if you cancel, the &quot;Track Statistics&quot; option will be un-checked..
        /// </summary>
        public static string Message_TrackStatisticsFolder {
            get {
                return ResourceManager.GetString("Message_TrackStatisticsFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Begin.
        /// </summary>
        public static string Range_Begin {
            get {
                return ResourceManager.GetString("Range_Begin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to End.
        /// </summary>
        public static string Range_End {
            get {
                return ResourceManager.GetString("Range_End", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number.
        /// </summary>
        public static string Range_Number {
            get {
                return ResourceManager.GetString("Range_Number", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fluence/Interrogation Solver Panel.
        /// </summary>
        public static string Tab_Fluence {
            get {
                return ResourceManager.GetString("Tab_Fluence", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Forward Solver/Analysis Panel.
        /// </summary>
        public static string Tab_ForwardSolver {
            get {
                return ResourceManager.GetString("Tab_ForwardSolver", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inverse Solver Panel.
        /// </summary>
        public static string Tab_InverseSolver {
            get {
                return ResourceManager.GetString("Tab_InverseSolver", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Map View.
        /// </summary>
        public static string Tab_MapView {
            get {
                return ResourceManager.GetString("Tab_MapView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Monte Carlo Solver Panel.
        /// </summary>
        public static string Tab_MonteCarlo {
            get {
                return ResourceManager.GetString("Tab_MonteCarlo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Plot View.
        /// </summary>
        public static string Tab_PlotView {
            get {
                return ResourceManager.GetString("Tab_PlotView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Spectral Panel.
        /// </summary>
        public static string Tab_Spectral {
            get {
                return ResourceManager.GetString("Tab_Spectral", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A.
        /// </summary>
        public static string Value_A {
            get {
                return ResourceManager.GetString("Value_A", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to b.
        /// </summary>
        public static string Value_b {
            get {
                return ResourceManager.GetString("Value_b", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Medium n.
        /// </summary>
        public static string Value_MediumN {
            get {
                return ResourceManager.GetString("Value_MediumN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Particle n.
        /// </summary>
        public static string Value_ParticleN {
            get {
                return ResourceManager.GetString("Value_ParticleN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Particle radius.
        /// </summary>
        public static string Value_ParticleRadius {
            get {
                return ResourceManager.GetString("Value_ParticleRadius", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Volume Fraction.
        /// </summary>
        public static string Value_VolumeFraction {
            get {
                return ResourceManager.GetString("Value_VolumeFraction", resourceCulture);
            }
        }
    }
}
